// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0K7nDC7FwLQdYohEcqDVwmBYfZrcjsS8',
    appId: '1:499397815592:web:d4c29144855acb4f50741d',
    messagingSenderId: '499397815592',
    projectId: 'tiktokclone-c0dde',
    authDomain: 'tiktokclone-c0dde.firebaseapp.com',
    storageBucket: 'tiktokclone-c0dde.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcYqkZvMzthcsjSkU3libVqlQBMNiyg5A',
    appId: '1:499397815592:android:1b04053b6e6372e150741d',
    messagingSenderId: '499397815592',
    projectId: 'tiktokclone-c0dde',
    storageBucket: 'tiktokclone-c0dde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqNrUB8jFKTu3koOxFQKBUSNWMatLvXRI',
    appId: '1:499397815592:ios:cfa1e297734291c050741d',
    messagingSenderId: '499397815592',
    projectId: 'tiktokclone-c0dde',
    storageBucket: 'tiktokclone-c0dde.appspot.com',
    iosClientId: '499397815592-pnrcaut36no1ss3coruu5jjdn7cbsfs2.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokNewClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqNrUB8jFKTu3koOxFQKBUSNWMatLvXRI',
    appId: '1:499397815592:ios:cfa1e297734291c050741d',
    messagingSenderId: '499397815592',
    projectId: 'tiktokclone-c0dde',
    storageBucket: 'tiktokclone-c0dde.appspot.com',
    iosClientId: '499397815592-pnrcaut36no1ss3coruu5jjdn7cbsfs2.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokNewClone',
  );
}
